### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Silph-Road** [NoxxDev/ONG-People#1]
Hi

**Comment by Silph-Road** [comment]
Can you activate the killswitch for your old necrobot repo?
Many ppl are trying to connect using that bot that uses old API. .39 is now minimum client.
They will all get banned as all apps were forced to .39 today.
I understand you will have to create repo and add killswitch txt file, but if you do you will help a lot of ppl from disappointment later on.

**Comment by NoxxDev** [comment]
ok

**Comment by Silph-Road** [comment]
Thanks a lot

**Comment by Silph-Road** [comment]
I would however suggest to remove or edit the message to error/incompatible API.
